### ISSUE TITLE
Window closing

### ISSUE THREAD

**Issue by ktb92677** [vurtun/gui#3] opened 2015-07-02 04:47 UTC
I'll start creating new issues for you :)

Anyways I'd like to also get the functionality to remove/add the minimize button on windows as well as program in exactly what happens when these buttons are clicked. Also I noticed that occasionally clicking on the status bar at the top of the window will close the window (even though I'm pretty sure I'm not clicking on the X).

Thanks!

**Comment by vurtun** [comment] 2015-07-02 11:45
Hey, ok round two.

I.) minimize icon hiding/showing
Adding and removing the minimize button can be achieved by setting or removing the `GUI_PANEL_MINIMIZABLE` flag in a panel. The demo already uses the functionality or is it not working for you?

II.) handling panel close/minimize button
The closing button sets the panel to hidden by adding the `GUI_PANEL_HIDDEN` flag to the panel. Furthermore the `gui_panel_begin` and `gui_panel_begin_xxx` calls return `gui_false` if the close button was pressed. So to check if the panel was closed by the user you can either check the panel flags or check the return argument of the `gui_panel_begin` calls. As for the demos the closing behavior of both panels is completly defined by the demo and not by the library. 

As for the minimize behavior the panel has a boolean flag `minimized` as well as a getter function `gui_panel_is_minimized`  to check if the panel is minimized. So while there is no direct way of checking if the minimize button was pressed, you can check if the minimize state has been changed.

If that is not enough and you need a more extensive way to check for state changes please let me now and give me a use case so I can further evaluate a better solution if needed. 

III.) close/minimize button bounding box
This was a problem for some time, but I hopefully fixed the issue. I had a small bug in the OpenGL font text width calculation code where I wrote `<=` instead of '<' and used the wrong width in the panel icon bounding box calculation. So clicking on the closing and minimizing icons should now work as intended.

**Comment by ktb92677** [comment] 2015-07-02 19:19
Hey! The close button and the minimize buttons are still clicking in the wrong place. It's almost as if the buttons are in the center of the title bar of the window.

Thanks for looking into this

**Comment by vurtun** [comment] 2015-07-02 19:44
Hmm. Which version do you use? I tested with opengl, xlib and nanovg since those are the one I can currently test and I don't seem to have the problem you describe.

**Comment by ktb92677** [comment] 2015-07-02 20:13
I am using just the .cpp and .h files in my own program. It is indeed very strange. It might actually have to do with my get text width function, I'm just realizing that you intended this to measure the full width of the string an not just the width of the characters. Silly mistake on my part

**Comment by vurtun** [comment] 2015-07-02 20:15
Ah OK, you really scared me there for a second,

**Comment by ktb92677** [comment] 2015-07-02 20:41
Ya sorry about that, this issue can be closed now... not sure exaclty if I can close these myself or if you have to do it

**Comment by vurtun** [comment] 2015-07-02 21:30
I will close it.

**Closed by vurtun** 2015-07-02 21:30 UTC
